# Generated by Django 5.1.1 on 2025-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_category_created_at_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
